package com.naukari.server.model.enums;

public enum FileType {
    RESUME, COVER_LETTER, PORTFOLIO, CERTIFICATE, COMPANY_LOGO, VERIFICATION_DOC, REGISTRATION_CERTIFICATE, TAX_CERTIFICATE, LICENSE, OTHER
}
